### ISSUE TITLE
Question: Refresh interval

### ISSUE THREAD

**Issue by peters** [mongodb/charts-embedding-examples#10]
@tomhollander 

Is it possible to set a global refresh interval (all embedded charts are affected) ? 
Is it possible to set refresh interval for a specific chart?

**Comment by tomhollander** [comment]
Hi @peters - no unfortunately there's no refresh option in the initial set of embedding features. However it's a great idea and we'll work on this ASAP.

**Comment by tomhollander** [comment]
Autorefresh and the ability to inject filters into charts should be available in early August.

**Comment by peters** [comment]
Thanks for getting back to me, Tom! Does this mean that you now may «scope» a chart to a specific organization? I.e say you have chart that displays today’s revenue for all organizations but want to limit the chart to a single organization for a specific user? ?filter=organizationId=objectId

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by tomhollander** [comment]
Yes that's how it will work. There is an open PR with updates to the samples that you can take a look at. These won't work until we deploy the changes to the Charts service next month though.

**Comment by peters** [comment]
@tomhollander Btw, will it be possible to localize the chart title (text chart) via this "api" ?

**Comment by tomhollander** [comment]
We plan on building a JavaScript SDK in the future, which should eventually give you programmatic control over chart elements including the title.

**Comment by tomhollander** [comment]
Autorefresh is implemented in Charts, and the samples in this repo have been updated.
