### ISSUE TITLE
How to pass objectId

### ISSUE THREAD

**Issue by Mangosteen-Yang** [mongodb/charts-embedding-examples#14]
Hi,

This example code works well thanks very much.

I am confused about how to pass `_id` in the filter.

for example:
```
const FILTER_DOCUMENT = {activity_id: ObjectId('5cf8a882f220081b355f288f')}
```
I will get `'ObjectId' is not defined ` error

I can pass through `"{activity_id: ObjectId('5cf8a882f220081b355f288f')}"` however, it is hard for me to assemble data like this.

**Comment by tomhollander** [comment]
Hey - can you try `{ activitiy_id: { $oid: '5cf8a882f220081b355f288f' } }` ?

**Comment by Mangosteen-Yang** [comment]
> Hey - can you try `{ activity_id: { $oid: '5cf8a882f220081b355f288f' } }` ?

Thanks.
I just tried today it works well.
